security:
    firewalls:
        # Firewall de la parte de administración o backend
        backend:
            pattern:        ^/admin
            provider:       administradores
            http_basic:     ~

        # Firewall de la extranet a la que se conectan las tiendas
        extranet:
            pattern:        ^/extranet
            provider:       tiendas
            anonymous:      ~
            form_login:
                login_path: /extranet/login
                check_path: /extranet/login_check
            logout:
                path:       /extranet/logout
                target:     /extranet

        # Firewall global utilizado en la parte pública o frontend
        frontend:
            pattern:        ^/*
            provider:       usuarios
            anonymous:      ~
            form_login:
                login_path: usuario_login
                check_path: usuario_login_check
            logout:
                path:       usuario_logout
            remember_me:
                secret:     cupon1234
                lifetime:   604800  # 604.800 = 3.600 * 24 * 7 = 1 semana

    access_control:
        - { path: ^/(es|en)/usuario/(login|registro), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(es|en)/usuario/*, roles: ROLE_USUARIO }
        - { path: ^/extranet/login,    roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/extranet/*,        roles: ROLE_TIENDA }
        - { path: ^/admin/*,           roles: ROLE_ADMIN }

    encoders:
        # el coste del algoritmo se ha reducido a 8 para que la carga de los datos
        # de prueba no sea demasiado lenta (se generan cientos de usuarios). En
        # una aplicación real, es mejor no cambiar el valor por defecto (que es 12)
        AppBundle\Entity\Usuario: { algorithm: bcrypt, cost: 8 }
        AppBundle\Entity\Tienda: { algorithm: bcrypt, cost: 8 }
        Symfony\Component\Security\Core\User\User: { algorithm: bcrypt, cost: 8 }

    providers:
        # Usuarios del frontend
        usuarios:
            entity: { class: AppBundle\Entity\Usuario, property: email }
        # Usuarios de la extranet
        tiendas:
            entity: { class: AppBundle\Entity\Tienda, property: login }
        # Usuarios del backend
        administradores:
            memory:
                users:
                    # usuario = admin, contraseña = 1234
                    admin: { password: '$2y$13$w700yeSs8FxMLrEXaCATgehosZf9vx09RbwKddswl9LN/22dKL2qO', roles: ROLE_ADMIN }

    role_hierarchy:
        ROLE_ADMIN: [ROLE_TIENDA, ROLE_USUARIO, ROLE_ALLOWED_TO_SWITCH]
