# Configuración global de los servicios de la aplicación
# Este archivo se importa desde app/config/config.yml
services:
    app.manager.usuario_manager:
        class: AppBundle\Manager\UsuarioManager
        arguments: ['@doctrine.orm.entity_manager', '@security.encoder_factory', '@security.token_storage']

    app.manager.tienda_manager:
        class: AppBundle\Manager\TiendaManager
        arguments: ['@doctrine.orm.entity_manager', '@security.encoder_factory']

    app.manager.oferta_manager:
        class: AppBundle\Manager\OfertaManager
        arguments: ['@doctrine.orm.entity_manager']

    app.security.oferta_voter:
        class: AppBundle\Security\CreadorOfertaVoter
        tags:
            - { name: security.voter }

    app.login_listener:
        class: AppBundle\Listener\LoginListener
        arguments: ['@security.authorization_checker', '@router']
        tags:
            - { name: kernel.event_listener, event: security.interactive_login }
            - { name: kernel.event_listener, event: kernel.response }

    app.twig.cupon_extension:
        class: AppBundle\Twig\Extension\CuponExtension
        tags:
            - { name: twig.extension }

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
